---
- name: Clone a WINDOWS VM from template | If HDD2 is not defined
  vmware_guest:
    validate_certs: no
    esxi_hostname: "{{ vmware_esx_host }}"
    datacenter: "{{ vmware_datacenter }}"
    datastore: "{{ vmware_datastore }}"
    folder: /
    name: "{{ vmware_hostname }}"
    state: poweredon
    disk:
    - size_gb: "{{ disksize1 }}"
      type: "{{ disktype }}"
      datastore: "{{ vmware_datastore }}"  
    hardware:
      memory_mb: "{{ memory_mb }}"
      num_cpus: "{{ num_cpus }}"
      scsi: paravirtual
    networks:
    - name: "{{ vmware_port_group }}"
      ip: "{{ vmware_ipaddress }}"
      netmask: "{{ vmware_netmask }}"
      gateway: "{{ vmware_gateway }}"
      type: static
      allow_guest_control: yes
      start_connected: yes
    customization:
      hostname: "{{ vmware_hostname }}"
      dns_servers: "{{ vmware_dns_server }}"
      timezone: "{{ timezone }}"
      joindomain: "{{ windows_domain }}"
      domainadmin: "{{ windows_domain_admin }}"
      domainadminpassword: "{{ windows_domain_admin_password }}"
    template: "{{ vmware_template_name }}"
    wait_for_customization: yes
    wait_for_ip_address: yes
  register: deploy_vm
  when: disksize2 is not defined

- name: Clone a WINDOWS VM from template | If HDD2 is defined
  vmware_guest:
    validate_certs: no
    esxi_hostname: "{{ vmware_esx_host }}"
    datacenter: "{{ vmware_datacenter }}"
    datastore: "{{ vmware_datastore }}"
    folder: /
    name: "{{ vmware_hostname }}"
    state: poweredon
    disk:
    - size_gb: "{{ disksize1 }}"
      type: "{{ disktype }}"
      datastore: "{{ vmware_datastore }}"
    - size_gb: "{{ disksize2 }}"
      type: "{{ disktype }}"
      datastore: "{{ vmware_datastore }}"   
    hardware:
      memory_mb: "{{ memory_mb }}"
      num_cpus: "{{ num_cpus }}"
      scsi: paravirtual
    networks:
    - name: "{{ vmware_port_group }}"
      ip: "{{ vmware_ipaddress }}"
      netmask: "{{ vmware_netmask }}"
      gateway: "{{ vmware_gateway }}"
      type: static
      allow_guest_control: yes
      start_connected: yes
    customization:
      hostname: "{{ vmware_hostname }}"
      dns_servers: "{{ vmware_dns_server }}"
      timezone: "{{ timezone }}"
      joindomain: "{{ windows_domain }}"
      domainadmin: "{{ windows_domain_admin }}"
      domainadminpassword: "{{ windows_domain_admin_password }}"
    template: "{{ vmware_template_name }}"
    wait_for_customization: yes
    wait_for_ip_address: yes
  register: deploy_vm
  when: disksize2 is defined