---
- name: Clone a LINUX VM from template
  vmware_guest:
    validate_certs: no
    esxi_hostname: "{{ vmware_esx_host }}"
    datacenter: "{{ vmware_datacenter }}"
    datastore: "{{ vmware_datastore }}"
    folder: /
    name: "{{ vmware_hostname }}"
    state: poweredon
    disk:
    - size_gb: "{{ disksize }}"
      type: "{{ disktype }}"
      datastore: "{{ vmware_datastore }}"          
    hardware:
      memory_mb: "{{ memory_mb }}"
      num_cpus: "{{ num_cpus }}"
      scsi: paravirtual
    networks:
    - name: "{{ vmware_port_group }}"
      ip: "{{ vmware_ipaddress }}"
      netmask: "{{ vmware_netmask }}"
      gateway: "{{ vmware_gateway }}"
      type: static
      allow_guest_control: yes
      start_connected: yes
    wait_for_ip_address: yes
    customization:
      hostname: "{{ vmware_hostname }}"
      dns_servers: "{{ vmware_dns_server }}"
    template: "{{ vmware_template_name }}"
    wait_for_customization: yes
    wait_for_customization_timeout: "3600"
    wait_for_ip_address: yes
    wait_for_ip_address_timeout: "600"
  register: deploy_vm