---
- name: Clone Linux VMs from template
  vmware_guest:
    validate_certs: false
    esxi_hostname: "{{ esx_host }}"
    datacenter: "{{ vmware_datacenter }}"
    datastore: "{{ vmware_datastore }}"
    folder: "{{ vmware_vm_folder }}/"
    name: "{{ vmware_hostname }}"
    state: poweredon
    disk:
    - size_gb: "{{ disksize }}"
      type: "{{ disktype }}"
      datastore: "{{ vmware_datastore }}"          
    hardware:
      memory_mb: "{{ memory_mb }}"
      num_cpus: "{{ num_cpus }}"
      scsi: paravirtual
    networks:
    - name: "{{ port_group }}"
      ip: "{{ ansible_host }}"
      netmask: "{{ netmask }}"
      gateway: "{{ gateway }}"
      type: static
      allow_guest_control: yes
      start_connected: yes
    wait_for_ip_address: yes
    customization:
      hostname: "{{ vmware_hostname }}"
      dns_servers: "{{ dns_server }}"
    template: "{{ vmware_template_name }}"
  register: deploy_vm